name: hicinterpolate
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip

  - numpy
  - scipy=1.10.1
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - networkx=3.2.1
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - tqdm=4.65.0
  - omegaconf=2.3.0

  - pip:
      - torch==2.1.1+cu118
      - torchvision==0.16.1+cu118
      - torchaudio==2.1.1+cu118
      - tensorflow==2.13.0

      # PyG
      - torch-geometric==2.5.3
      - torch-sparse==0.6.18
      - torch-scatter==2.1.2

      # GPU graph (pip wheels, CUDA 11)
      - cupy-cuda11x==13.3.0
      - cugraph-cu11

      # HiC / utilities
      - cooler
      - gensim
      - fastdtw
      - lpips
      - wandb
      - torchmetrics==1.7.1
