name: hici
channels:
  - pytorch
  - pyg
  - nvidia
  - rapidsai
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.8
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - cupy
  - cugraph
  - numpy
  - scipy=1.10.1
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - networkx=3.2.1
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - tqdm=4.65.0
  - omegaconf=2.3.0

  - pip:
      - tensorflow==2.13.0
      - torch-geometric==2.5.3
      - torch-sparse==0.6.18
      - torch-scatter==2.1.2
      - torchmetrics==1.7.1
      - lpips
      - wandb
      - cooler
      - gensim
      - fastdtw
