device: cuda

dir:
  root: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/testing
  model_state: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/testing/config
  output: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/testing/inference
  data: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/inference/kr_gf
  image: ${dir.data}/${data.patch}/

file:
  inference: ${dir.image}/human/dmso_control/control/0m_30m_60m/10000/21/dataset_dict.txt
  inference_raw: ${dir.image}/human/dmso_control/control/0m_30m_60m/10000/21/info.txt
  vgg_model: ${dir.data}/models/imagenet-vgg-verydeep-19.mat
  model: ${dir.model_state}/${model.name}.pt
  hic_map: ${dir.output}/${model.name}_inference_hic_map.jpg
  metrics: ${dir.output}/${model.name}_inference_metrics.txt
  log: ${dir.output}/${model.name}_inference.log

data:
  patch: 64
  interpolator_images_map:
    frame_0: img1.npy
    frame_2: img3.npy
  batch_size: 64

model:
  name: hicinterpolate_${data.patch}
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 4
  ext_feature_level: 3
  unique_levels: 2
  flow:
    num_of_convs: [7, 5, 7]
    out_channels: [16, 32, 64]
  fusion_pyramid_level: 4

loss:
  weight_parameters:
    - name: mse
      boundaries: [100]
      values: [1.0, 1.0]
    - name: symmetry
      boundaries: [100]
      values: [0.1, 0.5]
    - name: vgg
      boundaries: [100]
      values: [0.01, 0.1]